### PR TITLE
feat: highlight top langs

### PR DESCRIPTION
**Pull request by JialeTomTian**
image
 Let me know if the color and styling looks good

### CODE REVIEW

**Comment by ganler** [comment]
i feel the colors are not consistent row by row? probably because some even rows have a basic gray background.

**Comment by JialeTomTian** [comment]
O yeah you are right, I am seeing it now. Lemme see what I can do

**Comment by ganler** [comment]
one easy fix is to highlight the text not the bg?

**Comment by JialeTomTian** [comment]
image

**Review by ganler — APPROVED** [review]

**Comment by ganler** [comment]
just to check: did you do pre-commit

**Comment by ganler** [comment]
`pre-commit run --all-files`

**Pull request merged**
